import {useEffect,useState,type CSSProperties} from 'react';
import {Link,Route,Routes,useLocation} from 'react-router-dom';
import sourceConfig from './config.generated.json';
import {Config,eventDates,formatDate,navigation,PersonContact} from './types';
import {api} from './api';
import {EventBanner} from './components/EventBanner';import {EventNavigation} from './components/EventNavigation';
import {InfoCard} from './components/InfoCard';import {ContentSection} from './components/ContentSection';
import {AgendaTables} from './components/AgendaTables';import {MobileServiceDock} from './features/learner/MobileServiceDock';
import {Account} from './Account';
const config=sourceConfig as Config;
const noun=config.event.title.includes('实训营')?'实训营':config.event.title.includes('论坛')?'论坛':'会议';
const numerals=['一','二','三','四','五','六','七','八','九','十'];
function ContactList({contacts}:{contacts:PersonContact[]}){const groups=[...new Set(contacts.map(x=>x.responsibility))];return <div className="contact-list">{groups.map(group=><section className="contact-group" key={group}><h3>{group}</h3><ul>{contacts.filter(x=>x.responsibility===group).map((p,i)=><li key={i}><strong>{p.name}</strong>{p.email&&<span><a href={`mailto:${p.email}`}>{p.email}</a></span>}{p.phone&&<span><a href={`tel:${p.phone}`}>{p.phone}</a></span>}{p.note&&<small>{p.note}</small>}</li>)}</ul></section>)}</div>}
function Home(){const sections:{key:string;title:string;body:React.ReactNode}[]=[{key:'intro',title:`${noun}简介`,body:<>{config.home.intro.map((p,i)=><p key={i}>{p}</p>)}{config.home.target&&<p>{config.home.target}</p>}</>}];
 if(config.home.features.length)sections.push({key:'features',title:`${noun}特色`,body:<div className="feature-list">{config.home.features.map((f,i)=><article key={i}><h3>{f.title}</h3><p>{f.description}</p></article>)}</div>});
 if(eventDates(config)||config.event.location)sections.push({key:'time',title:'举办时间与地点',body:<>{eventDates(config)&&<p>{noun}日期：{eventDates(config)}</p>}{(config.event.startAt||config.event.endAt)&&<p>具体时刻：{[config.event.startAt,config.event.endAt].filter(Boolean).map(x=>formatDate(x,config.event.timezone)).join(' 至 ')}</p>}{config.event.location&&<p>举办地点：{config.event.location}</p>}</>});
 sections.push({key:'agenda',title:'日程安排',body:<AgendaTables agenda={config.agenda}/>});
 if(config.home.organizers.length)sections.push({key:'organizations',title:'组织单位',body:<div className="organization-groups">{[...new Set(config.home.organizers.map(x=>x.role))].map(role=><section className="organization-group" key={role}><h3>{role}</h3><ul>{config.home.organizers.filter(x=>x.role===role).map((x,i)=><li key={i}>{x.name}</li>)}</ul></section>)}</div>});
 sections.push({key:'registration',title:'报名与投稿',body:<div className="home-registration"><p>参会报名与在线投稿是独立入口。普通参会者无需投稿；投稿录用后自动获得参会资格。</p>{config.attendance.closeAt&&<p>报名截止：{formatDate(config.attendance.closeAt,config.event.timezone)}</p>}{config.submission.closeAt&&<p>投稿截止：{formatDate(config.submission.closeAt,config.event.timezone)}</p>}<p className="registration-cta-wrap"><Link className="registration-cta" to="/account">进入个人中心</Link></p></div>});
 if(config.travel.address)sections.push({key:'travel',title:'食宿与交通',body:<><p>{config.travel.address}</p><p className="home-travel-notice__link"><Link to="/travel">查看交通住宿说明</Link></p></>});
 if(config.contacts.length)sections.push({key:'contact',title:'联系方式',body:<ContactList contacts={config.contacts}/>});
 return <div className="home-page">{sections.map((s,i)=><ContentSection key={s.key} title={`${numerals[i]}、${s.title}`}>{s.body}</ContentSection>)}</div>}
function Travel(){return <section className="public-page__section" aria-label="交通住宿"><div className="travel-sections"><article className="travel-section"><h3>{noun}地址</h3><div className="travel-section__body"><p>{config.event.location}</p>{config.travel.address&&config.travel.address!==config.event.location&&<p>{config.travel.address}</p>}{config.travel.mapUrl&&<p><a href={config.travel.mapUrl} target="_blank" rel="noreferrer">查看位置地图</a></p>}</div></article>{config.travel.directions.map((x,i)=><article className="travel-section" key={i}><h3>{x.title}</h3><div className="travel-section__body"><p>{x.body}</p></div></article>)}{!!config.mealGuide?.length&&<article className="travel-section"><h3>食宿指引</h3>{config.mealGuide.map((x,i)=><div className="hotel-info" key={i}><h4>{x.title}</h4><p>{x.body}</p></div>)}</article>}{!!config.hotels.length&&<article className="travel-section"><h3>住宿信息</h3>{config.hotels.map((x,i)=><div className="hotel-info" key={i}><h4>{x.name}</h4><p>{x.address}</p><p>{x.description}</p>{x.url&&<a href={x.url} target="_blank" rel="noreferrer">查看酒店信息</a>}</div>)}</article>}{config.resources.filter(x=>x.type==='map').map((x,i)=><article className="travel-section" key={`map-${i}`}><h3>{x.title}</h3><figure className="travel-map"><img src={x.url||x.asset} alt={x.title}/><figcaption>{x.description}</figcaption></figure></article>)}</div></section>}
function Resources(){return <section className="public-page__section" aria-label="相关资料"><h2>相关资料</h2><div className="resource-list">{config.resources.map((x,i)=><InfoCard key={i} title={x.title} variant="compact"><p>{x.description}</p><a href={x.url||x.asset} target="_blank" rel="noreferrer">查看 / 下载{x.type?`（${x.type}）`:''}</a></InfoCard>)}{!config.resources.length&&<p>暂无公开资料。</p>}</div>{config.event.recordingsEnabled&&<ContentSection title={`${noun}录播`}>{config.recordings.map((x,i)=><InfoCard key={i} title={x.title} variant="compact"><p>{x.description}</p><a href={x.url} target="_blank" rel="noreferrer">观看录播</a></InfoCard>)}</ContentSection>}<p className="auth-help">本页仅列出公开资料；个人投稿附件不会公开。</p></section>}
function Faq(){return <section className="faq-page"><header className="faq-page__header"><div><h2>常见问题</h2><p>报名、投稿与会务事项说明</p></div></header>{!!config.notices?.length&&<section className="faq-article" aria-label="参会须知"><h2>参会须知</h2>{config.notices.map((x,i)=><article key={i}><h3>{x.title}</h3><p style={{whiteSpace:'pre-line'}}>{x.body}</p></article>)}</section>}<div className="faq-article">{config.faqs.map((x,i)=><article key={i}><h3>{i+1}. {x.question}</h3><p>{x.answer}</p></article>)}</div>{!config.faqs.length&&<p className="faq-empty">暂无问题。</p>}</section>}
export function App({preview=false}:{preview?:boolean}={}){const location=useLocation();const [authenticated,setAuthenticated]=useState(false);
 useEffect(()=>{document.title=`${config.event.shortTitle||config.event.title} · ${navigation.find(x=>x.to===location.pathname)?.label||'活动服务'}`;window.scrollTo(0,0)},[location.pathname]);
 useEffect(()=>{if(preview)return;let active=true;if(location.pathname!=='/account')api('/api/me/profile').then(()=>{if(active)setAuthenticated(true)}).catch(()=>{if(active)setAuthenticated(false)});return()=>{active=false}},[preview,location.pathname]);
 const entry={label:authenticated?'个人中心':'登录／注册',to:'/account?mode=login'};
 const datesCard=(eventDates(config)||config.attendance.closeAt||config.submission.closeAt)?<InfoCard title="重要日期"><dl className="date-list">{eventDates(config)&&<div><dt>{noun}日期</dt><dd>{eventDates(config)}</dd></div>}{config.attendance.closeAt&&<div><dt>报名截止</dt><dd>{formatDate(config.attendance.closeAt,config.event.timezone)}</dd></div>}{config.submission.closeAt&&<div><dt>投稿截止</dt><dd>{formatDate(config.submission.closeAt,config.event.timezone)}</dd></div>}</dl></InfoCard>:null;
 const brandStyle=config.branding.primaryColor?({'--panshi-color-primary':config.branding.primaryColor,'--panshi-gradient-primary':`linear-gradient(135deg, ${config.branding.primaryColor} 0%, #9fd4c4 100%)`} as CSSProperties):undefined;
 const organizers=config.home.organizers.filter(x=>['主办单位','主办'].includes(x.role));const contactGroups=[...new Set(config.contacts.map(x=>x.responsibility))];
 return <div className="public-shell" style={brandStyle}><a className="skip-link" href="#main-content">跳到主要内容</a><EventBanner title={config.event.title} titleHref="/" dates={eventDates(config)} venue={config.event.location} image={config.branding.heroImage?{src:config.branding.heroImage,width:2048,height:512}:undefined}/><EventNavigation items={navigation}/><div className="event-container public-layout" data-testid="desktop-content-sidebar"><main id="main-content" tabIndex={-1}><Routes><Route path="/" element={<Home/>}/><Route path="/travel" element={<Travel/>}/><Route path="/contact" element={<section className="public-page__section" aria-label="联系我们"><ContactList contacts={config.contacts}/></section>}/><Route path="/resources" element={<Resources/>}/><Route path="/faq" element={<Faq/>}/><Route path="/account" element={<Account config={config} offline={preview} onSessionChange={setAuthenticated}/>}/><Route path="*" element={<section className="placeholder-page"><h2>页面不存在</h2><Link to="/">返回首页</Link></section>}/></Routes></main><aside className="public-sidebar" aria-label="活动补充信息">{location.pathname!='/account'&&<Link className="registration-cta sidebar-cta" to={entry.to}>{entry.label}</Link>}{datesCard}</aside></div><MobileServiceDock entry={entry}>{datesCard}</MobileServiceDock><footer className="event-footer"><div className="event-container event-footer__grid"><section><h2>{config.event.shortTitle}</h2>{!!organizers.length&&<p>主办单位：{organizers.map(x=>x.name).join('、')}</p>}<p>{config.event.subtitle}</p></section><section><h2>联系咨询</h2>{contactGroups.map(group=><div className="event-footer__contact" key={group}><strong>{group}</strong>{config.contacts.filter(x=>x.responsibility===group).map((x,i)=><span key={i}>{x.name} {x.email||x.phone}</span>)}</div>)}</section><nav aria-label="页脚导航"><h2>快速入口</h2><Link to="/">活动首页</Link><Link to="/resources">相关资料</Link><Link to="/travel">交通住宿</Link><Link to="/account">个人中心</Link></nav></div><div className="event-container event-footer__legal"><span>© {(config.event.startDate||config.event.startAt||'').slice(0,4)} {config.event.shortTitle}会务组</span></div></footer></div>
}
